### ISSUE TITLE
Preview Inspector elements should use up available vertical realestate

### ISSUE THREAD

**Issue by ssshake** [ProcessMaker/spark-screen-builder#171]
![image](https://user-images.githubusercontent.com/1675868/57803144-b115c500-7725-11e9-8c85-1fee1c89d1e6.png)

**Comment by tuantruong625** [comment]
- Not as simple as setting `h-50` on data input and preview because of the headers
- setting the height of the text-area dynamically without modifying vue-form-elements repo 

@velkymx Will continue on Tuesday

<img width="1674" alt="Screen Shot 2019-05-17 at 6 09 00 PM" src="https://user-images.githubusercontent.com/26545455/57958910-7fd8f880-78cf-11e9-8aa1-b065358eb98d.png">

**Comment by tuantruong625** [comment]
@velkymx 

The transitions on the accordions are broken because to fill the remaining space when collapsed / close with the data input & preview we set the accordions to a flex container. Which breaks the transitions because it relies on the height of the container to make the transition.

**Video with broken transition**
https://drive.google.com/open?id=1fsWA5OLfUPj-4E-jfCC2VFTs_US4NWFM

To fix the transitions on the accordions will require more work with javascript.

The comprise is setting a fixed height on the data input / preview containers. The only issue is when there is an overflow with the data input there will be double scroll bars. As shown in the screenshot.

<img width="1680" alt="Screen Shot 2019-05-21 at 4 09 05 PM" src="https://user-images.githubusercontent.com/26545455/58131797-947a0100-7bed-11e9-90c0-2b197bc2766a.png">

Do we want to invest more time to fix the animations ?

**Current Implementation**
Or have the data input / preview accordion to behave like the script editor accordions ?
