### ISSUE TITLE
Default Value Not Set

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/spark-screen-builder#193]
The default selected value for a checkbox or radio group is not being sent in the data. You need to change it and change it back to set the data.

Elements to fix/verify:

- [ ] Radio groups
- [ ] Checkboxs
- [ ] Checkbox groups?
- [ ] Selects

**Comment by ssshake** [comment]
This should also apply to selects because for now selects just work around the issue by hard coding an <option>Select...</option> 

which forces people to pick something else in the list, which then sets the value properly. This 'Select...' should not have to be there. It should be removed, and whatever the default/first option is in the list, should be properly set without needing a user to click on it.
