### ISSUE TITLE
Select Default Value

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/spark-screen-builder#194]
The default "Select..." for a select element is not there. We fixed that in vue-form-elements but it didn't get into screen builder for some reason. Maybe update to latest form-elements?

**Comment by chipit24** [comment]
This appears to be fixed with the latest `vue-form-elements`, but `spark-screen-builder` is already pointing to the latest _published_ version of that package (`0.9.0`). The commit containing the fix is not part of the previous release.

Here is a video of it working in spark, with `vue-form-elements` npm link'ed in:
https://www.dropbox.com/s/afzyxll0owsm11j/form_select.mov?dl=0

@velkymx @caleeli Once a new version of `vue-form-elements` in published, it can be pulled it.
