### ISSUE TITLE
Text Colors Not Working

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/spark-screen-builder#223]
This is true of both the Variant select as well as using a custom CSS class with the color CSS attribute.

<img width="1244" alt="Screenshot 2019-06-04 08 49 34" src="https://user-images.githubusercontent.com/535300/58893856-c4251080-86a5-11e9-9781-b2196a9edc8a.png">

**Comment by velkymx** [comment]
https://www.dropbox.com/s/bpxmkwe129udl0a/sb-font-colors.mov?dl=0

**Comment by tuantruong625** [comment]
@velkymx In stand alone builder the text colour selector works. The reason why the text colour does not work in Spark is because there is an issue with specificity. In `app.scss`, the form-group/checkbox labels, are being set as `#788793`. The quick fix is removing the colour overwrites on the labels.

**Spark Video Demo**
- default colour of form-group label is dark
https://drive.google.com/open?id=1qYxgUKY56c6yfIDGx8hZL78NdZVJMxox

Do we keep the label colour the same (#788793)?
or Remove the colour overwrite and move forward?
